### ISSUE TITLE
Magic chars in StringPattern character groups behaving incorrectly

### ISSUE THREAD

**Issue by Fish013** [wizards-of-lua/rembulan#4]
```lua
string.match(tostring(0.5), "([^05+])") 
``` 
is giving a 

```
Caused by: java.lang.IllegalArgumentException: error at character 6: unexpected character '+'
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.parseError(StringPattern.java:941)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.CC_lit(StringPattern.java:1087)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.characterSetElement(StringPattern.java:1017)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.characterSetBody(StringPattern.java:1025)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.cclass(StringPattern.java:1133)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.PI_cc(StringPattern.java:1163)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.PI(StringPattern.java:1186)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.PI_capture(StringPattern.java:1196)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.PI(StringPattern.java:1170)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.parse(StringPattern.java:1218)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.access$900(StringPattern.java:913)
	at net.sandius.rembulan.lib.StringPattern.fromString(StringPattern.java:1228)
	at net.sandius.rembulan.lib.StringPattern.fromString(StringPattern.java:1232)
	at net.sandius.rembulan.lib.StringLib$Match.invoke(StringLib.java:1699)
	at net.sandius.rembulan.lib.AbstractLibFunction.invoke(AbstractLibFunction.java:39)
	at net.sandius.rembulan.runtime.AbstractFunctionAnyArg.invoke(AbstractFunctionAnyArg.java:36)
	at net.sandius.rembulan.runtime.Dispatch.mt_invoke(Dispatch.java:70)
	at net.sandius.rembulan.runtime.Dispatch.call(Dispatch.java:236)
```

when it should execute successfully and handle the + char as it is in the character group.

See https://www.lua.org/manual/5.3/manual.html#6.4.1 in the section '[set]' where it is stated that 

> "All other characters [except '-' and escaped character classes] in set represent themselves"

**Comment by Fish013** [comment]
While making further tests on https://www.lua.org/cgi-bin/demo it seems even '-' does not need to be escaped if it forms no character range

**Comment by mkarneim** [comment]
Confirmed - this looks like a bug.

Here is a simplified reproducer that produces the same error: `string.match("+" ,"[+]")`

```
java.lang.IllegalArgumentException: error at character 2: unexpected character '+'
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.parseError(StringPattern.java:941)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.CC_lit(StringPattern.java:1087)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.characterSetElement(StringPattern.java:1017)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.characterSetBody(StringPattern.java:1025)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.cclass(StringPattern.java:1140)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.PI_cc(StringPattern.java:1163)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.PI(StringPattern.java:1186)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.parse(StringPattern.java:1218)
	at net.sandius.rembulan.lib.StringPattern$PatternBuilder.access$0(StringPattern.java:1212)
	at net.sandius.rembulan.lib.StringPattern.fromString(StringPattern.java:1228)
	at net.sandius.rembulan.lib.StringPattern.fromString(StringPattern.java:1232)
	at net.sandius.rembulan.lib.StringLib$Match.invoke(StringLib.java:1699)
	at net.sandius.rembulan.lib.AbstractLibFunction.invoke(AbstractLibFunction.java:39)
```

**Comment by Adrodoc** [comment]
Duplicate of mjanicek#17.

**Comment by Fish013** [comment]
maybe i should start by looking in the original repo, thx for the info
